apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-serv
spec:
  type: NodePort
  selector:
      app: nginx
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80

---
#cluster ip for internal communication
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-serv
spec:
  selector:
    app: nginx               # Matches the 'app: nginx' label from your Deployment
  ports:
    - port: 80               # The port that the service will expose internally in the cluster
      targetPort: 80 