apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  
spec:
  containers:
  - name: resource-demo
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu","2","--vm","1","--vm-bytes","80GB","--vm-hang","1"]
    resources:
      requests:
        cpu: "1"
        memory: "10Gi"
      limits:
        cpu: "2"
        memory: "20Gi"