kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userd-binding
  namespace: developments
subjects:
- kind: User
  name: userd
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: userd-role
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: userp-binding
  namespace: production
subjects:
- kind: User
  name: userp
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: userp-role
  apiGroup: rbac.authorization.k8s.io