apiVersion: v1
kind: Secret
metadata:
  name: docker-psd
type: Opaque
stringData:
  credentials: |
    [default]
    docker_username=saxenarajat499
    docker_psd=qwe123qwe1213

---
apiVersion: v1
kind: Pod
metadata:
  name: secrets
spec:
  containers:
  - name: secrets-pod
    image: saxenarajat499/testings:worker
    volumeMounts:
    - name: docker-psd
      mountPath: /etc/docker/
      readOnly: true
  volumes:
  - name: docker-psd
    secret:
      secretName: docker-psd
